<a href="https://colab.research.google.com/github/sevensixteeeen/Pandas-lib./blob/main/non_online_storedata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mashlyn/online-retail-ii-uci")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'online-retail-ii-uci' dataset.
Path to dataset files: /kaggle/input/online-retail-ii-uci

In [30]:
import os
print(os.listdir(path))

['online_retail_II.csv']

In [31]:
import pandas as pd
import numpy as np
df=pd.read_csv(path+"/online_retail_II.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [32]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

(1067371, 8)

In [33]:
df.isna().sum()
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [34]:
df = df.rename(columns={
    "Customer ID": "customer_id",
    "Price": "unit_price",
    "Invoice": "invoice",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "Country": "country",
})
print(df)

        invoice stock_code                          description  quantity  \
0        489434      85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434     79323P                   PINK CHERRY LIGHTS        12
2        489434     79323W                  WHITE CHERRY LIGHTS        12
3        489434      22041         RECORD FRAME 7" SINGLE SIZE         48
4        489434      21232       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...        ...                                  ...       ...
1067366  581587      22899         CHILDREN'S APRON DOLLY GIRL          6
1067367  581587      23254        CHILDRENS CUTLERY DOLLY GIRL          4
1067368  581587      23255      CHILDRENS CUTLERY CIRCUS PARADE         4
1067369  581587      22138        BAKING SET 9 PIECE RETROSPOT          3
1067370  581587       POST                              POSTAGE         1

                invoice_date  unit_price  customer_id         country
0        2009-12-01 07:45:00        6.95      13085.0  United Kingdom
1        2009-12-01 07:45:00        6.75      13085.0  United Kingdom
2        2009-12-01 07:45:00        6.75      13085.0  United Kingdom
3        2009-12-01 07:45:00        2.10      13085.0  United Kingdom
4        2009-12-01 07:45:00        1.25      13085.0  United Kingdom
...                      ...         ...          ...             ...
1067366  2011-12-09 12:50:00        2.10      12680.0          France
1067367  2011-12-09 12:50:00        4.15      12680.0          France
1067368  2011-12-09 12:50:00        4.15      12680.0          France
1067369  2011-12-09 12:50:00        4.95      12680.0          France
1067370  2011-12-09 12:50:00       18.00      12680.0          France

[1067371 rows x 8 columns]